### PR TITLE
'verifyUriSyntax' option which can disable import failures on bad uris

### PR DESCRIPTION
**Pull request by manonthegithub**
Using the plugin we encountered an issue that it fails importing if encounters bad uri. 
In our case we can not fix all the wrong uris and there is no guarantee for always right uris in our dataset.
I have added optional option 'verifyUriSyntax' which can disable uri syntax check which is done by default.

It would be fine if we could issue a release in a week or so.

### CODE REVIEW

**Comment by manonthegithub** [comment]
refs #76

**Comment by manonthegithub** [comment]
@jbarrasa Thanks a lot for your time in advance.

**Comment by jbarrasa** [comment]
Thanks for your contribution @manonthegithub !
Are you aware of a similar config param in RDF4J that relaxes the policy on loading literal values of type `rdf:langString` but without a lang tag? 
If I try to load the Turtle fragment below, Rio crashes with a `"datatype rdf:langString requires a language tag [line 4]"` message. Any help appreciated :)

```@prefix dbr:	<http://dbpedia.org/resource/> .
@prefix dbo:	<http://dbpedia.org/ontology/> .
@prefix dbp:	<http://dbpedia.org/property/> .
dbr:Ciena	dbp:locationCountry	"United States"^^rdf:langString ;
	dbo:locationCity	<http://dbpedia.org/resource/Hanover,_Maryland> .

**Comment by manonthegithub** [comment]
@jbarrasa hmmm... I don't, but I will try to find what can we do with it! I also forgot to make a documentation for this feature, I will submit a pr for it a well:).

**Comment by manonthegithub** [comment]
> Are you aware of a similar config param in RDF4J that relaxes the policy on loading literal values of type rdf:langString but without a lang tag?

@jbarrasa it seems that if you don't have language tag it is wrong RDF. Here are the [docs](https://www.w3.org/TR/rdf11-concepts/#dfn-language-tagged-string). I am not sure it is possible to relax this. How do you determine a language if there is no lang tag?

**Comment by manonthegithub** [comment]
> Are you aware of a similar config param in RDF4J that relaxes the policy on loading literal values of type rdf:langString but without a lang tag?

It seems there is not such an option:

https://github.com/eclipse/rdf4j/blob/1abe4fe5ba37e4ce19aaa294314c74bec68531c8/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleLiteral.java#L91-99

**Pull request merged**
